<a href="https://colab.research.google.com/github/seungm2n/PythonTest/blob/main/3_DataFrame_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

agg_prd_df = pd.DataFrame({
    'L' : [5141, 5365, 5084],
    'M' : [4968, 4977, 4915],
    'S' : [5012, 4991, 5029],
    'XL' : [5071, 4976, 5023],
    'XS' : [5195, 4954, 5088]
}, index= ['Jacket','Shirt','Trousers'])

agg_prd_df

             L     M     S    XL    XS
Jacket    5141  4968  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088

In [ ]:
agg_prd_df.iloc[0, 1]

4968

In [ ]:
agg_prd_df.iloc[0, 1] = 5000
agg_prd_df

             L     M     S    XL    XS
Jacket    5141  5000  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088

In [ ]:
agg_prd_df.iloc[:, 1:3]

             M     S
Jacket    5000  5012
Shirt     4977  4991
Trousers  4915  5029

In [ ]:
agg_prd_df.loc['Jacket', 'M']

5000

In [ ]:
agg_prd_df.loc['Shirt':'Trousers', 'L':'S']

             L     M     S
Shirt     5365  4977  4991
Trousers  5084  4915  5029

In [ ]:
agg_prd_df.loc['Shirt':'Trousers', ['XL','S']]

            XL     S
Shirt     4976  4991
Trousers  5023  5029

In [ ]:
agg_prd_df

             L     M     S    XL    XS
Jacket    5141  5000  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088